# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelmRestore < Formula
  desc "A CLI to restore your helm charts"
  homepage "https://github.com/si3nloong/helm-restore"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/si3nloong/helm-restore/releases/download/v1.0.2/helm-restore_Darwin_arm64.tar.gz"
      sha256 "0a3ac7779233e174e9659914f6fa256758595d00e0f70102fbc900804fd04beb"

      def install
        bin.install "helm-restore"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/si3nloong/helm-restore/releases/download/v1.0.2/helm-restore_Darwin_x86_64.tar.gz"
      sha256 "c74dd7d64f64f5e098bfdbb1fd4ace1567e41efa41f0f0b11fd17cd4060f4b5e"

      def install
        bin.install "helm-restore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/si3nloong/helm-restore/releases/download/v1.0.2/helm-restore_Linux_x86_64.tar.gz"
      sha256 "9979fb30c704d0826c35e9a2ef56c01ea60fdb411d9d8e99e56716c5d4adce77"

      def install
        bin.install "helm-restore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/si3nloong/helm-restore/releases/download/v1.0.2/helm-restore_Linux_arm64.tar.gz"
      sha256 "2fc2ccb9d64ac851df87e707342d32f9e7249e43f17a177e8353571601bdd009"

      def install
        bin.install "helm-restore"
      end
    end
  end
end
